version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: devcollab-postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devcollab-network
    command: ["postgres", "-c", "ssl=off"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: devcollab-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    networks:
      - devcollab-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devcollab-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=${API_URL}
    networks:
      - devcollab-network
    depends_on:
      - backend

networks:
  devcollab-network:
    driver: bridge

volumes:
  postgres_data:
