name: Deploy Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Stop existing containers
        run: |
          docker-compose -f docker-compose.prod.yml down || true

      - name: Remove existing images
        run: |
          docker image prune -f

      - name: Build and start containers
        run: |
          docker-compose -f docker-compose.prod.yml up -d --build
        env:
          VITE_API_URL: http://209.38.243.102

      - name: Clean up
        run: |
          docker image prune -f
